name: Build and publish to Docker Hub (releases only)
on:
  push:
    branches:
      - master
    
jobs:
  build:
    name: build latest images for relase
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Push openvpn image to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          tags: openvpn-latest
          dockerfile:  Dockerfile.openvpn
      - name: Push ovpn-admin image to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          tags: latest
          dockerfile: Dockerfile
