name: Build and publish to Docker Hub (releases only)
on:
  push:
    branches:
      - master
    
jobs:
  build:
    name: build latest images for relase
    runs-on: ubuntu-latest
    steps:
      - name: Push openvpn image to Docker Hub
        uses: docker/build-push-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          tags: avapno/ovpn-admin:openvpn-latest
          dockerfile:  Dockerfile.openvpn
      - name: Push ovpn-admin image to Docker Hub
        uses: docker/build-push-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          tags: avapno/ovpn-admin:latest
          dockerfile: Dockerfile
